<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MockUnitMode" Id="{23f7f16b-0a3d-0438-2fe0-39f9efc55b06}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK MockUnitMode EXTENDS DefaultUnitMode<State.Idle>
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="StateComplete" Id="{527ee925-d6c9-01e9-1630-82e9efd9b109}">
      <Declaration><![CDATA[METHOD PUBLIC StateComplete]]></Declaration>
      <Implementation>
        <ST><![CDATA[state_machine.StateComplete();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>